author: TechMastary
database: false
description: Is chat going out of hand? Disable the use of global chat!
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.techmastary.plugins.chatmaster.ChatMaster
name: ChatMaster
startup: postworld
url: http://TechMastary.net/
version: '1.0'
commands:
  silence:
    description: Toggle the use of global chat.
    permission: silenced.admin
    usage: /[command]
  chatstatus:
    description: Check the status of global chat.
    permission: silenced.admin
    usage: /[command]
permissions:
  silenced.admin:
    description: Have access to all features and be able to speak in global chat when disabled.
  silenced.speak:
    description: Be able to speak in global chat while disabled.