author: TechMastary
database: false
description: Is chat going out of hand? Disable the use of global chat!
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.techmastary.plugins.chatmaster.ChatMaster
name: ChatMaster
startup: postworld
url: http://TechMastary.net/
version: '1.1.3'
commands:
  cm:
    description: ChatMaster base command.
    usage: /[command]
permissions:
  chat.silence:
    description: Have access to all features and be able to speak in global chat when disabled.
  chat.speak:
    description: Be able to speak in global chat while disabled.
  chat.status:
    description: Check the status of global chat.
  chat.clean:
    description: Clean your own chat.