author: TechMastary
database: false
description: Is chat going out of hand? Disable the use of global chat!
main: net.techmastary.plugins.chatmaster.ChatMaster
name: ChatMaster
startup: postworld
url: http://TechMastary.net/
version: '1.2'
commands:
  cm:
    description: ChatMaster base command.
    usage: /[command] <args>
  ping:
    description: Pings player.
    usage: /[command] <player>
permissions:
  chat.silence:
    description: Have access to all features and be able to speak in global chat when disabled.
  chat.speak:
    description: Be able to speak in global chat while disabled.
  chat.status:
    description: Check the status of global chat.
  chat.clean:
    description: Clean your own chat.